# Generated by Django 3.0.5 on 2020-05-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project1',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project1',
            name='discription',
            field=models.TextField(max_length=250),
        ),
    ]
