# Generated by Django 3.0.5 on 2020-05-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200501_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project1',
            name='discription',
            field=models.TextField(max_length=1000),
        ),
    ]
